### ISSUE TITLE
에디터 구현문제

### ISSUE THREAD

**Issue by yk1028** [boostcamp3-iOS/team-a2#2]
테이블 뷰를 이용해서 구현하려고 시도했지만 전체 선택 기능구현이 힘들 것 같다.
기존 DayOne 앱에서는 전체선택으로 모든 텍스트와 이미지가 선택되는 것으로보아 전체가 텍스트 뷰로 이루어진 것 같다.

**Comment by caution-dev** [comment]
## 해결됨
UITextView와 UITextDragDelegate 를 통해 Drag & Drop 기능 구현 > Pull Request #4 
NSAttributedText 를 사용하여 UITextView에 이미지 삽입. > Pull Request #5 
Drag 시 이미지와 텍스트 Preview 보여주기 > Pull Request #6
